# Generated by Django 4.2 on 2023-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_pag',
            field=models.IntegerField(blank=True, default=0, verbose_name='número de páginas'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
